---
title: "Gene_Importance_modification"
output: html_document
date: "2025-06-05"
note: "This script modifies the feature importance files to remove the aneuploidy feature cis-genes from teh importance output and save the modified files."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "D:/projects/HetIN_signatures/")
```


Load the packages
```{r}
library(tidyverse)
library(ggplot2)
library(rtracklayer)
library(GenomicRanges)

```

```{r}
# Define the cancer types
can_types <- c("BRCA", "LUAD", "LUSC", "HNSC")

# folder with the feature importance files
feat_imp_folder_pre <- "data/Cancer_specific_data/Model_output"
feat_imp_folder_post <- "Results/Feature_importance/Base_feat_imp"

# Load the gene annotations 
gene_annotations <- read.csv("data/secondary_data/gene_seqnames_nnotation_df.csv", stringsAsFactors = FALSE, row.names = NULL)

# Load the gene_set genes
gene_set_genes <- read.csv("data/secondary_data/Gene_set.csv", stringsAsFactors = FALSE)
gene_set <- colnames(gene_set_genes)
rm(gene_set_genes)
```

```{r}
# reduce the gene annotations to the genes that are in the set of interest
gene_annotations <- gene_annotations %>%
  filter(gene_name %in% gene_set)
```


```{r}
for (cancer in can_types) {
  cat("\n\n\n", cancer)
  
  # Define the folders for the feature importance files
  feat_imp_folder <- file.path(feat_imp_folder_pre, cancer, feat_imp_folder_post)
  complete_imp_folder <- file.path(feat_imp_folder, "complete")
  filt_imp_folder <- file.path(feat_imp_folder, "filtered")
  ori_imp_folder <- file.path(feat_imp_folder, "original")
  
  # Create the complete and filtered folders if they do not exist
  if (!dir.exists(complete_imp_folder)) {
    dir.create(complete_imp_folder, recursive = TRUE)
  }
  if (!dir.exists(filt_imp_folder)) {
    dir.create(filt_imp_folder, recursive = TRUE)
  }
  
  complete_cancer_type_imp_df <- data.frame()
  filtered_cancer_type_imp_df <- data.frame()
  
  # Loop through each feature importance files in the folder
  for (feature_file in list.files(ori_imp_folder, full.names = TRUE)[38:45]) {
      # cat("\n\n", feature_file)
      
      # Get the feature from the name
      file_name <- basename(feature_file)
      # cat("\n File name: ", file_name)
      
      name_split <- str_split(file_name, "_")[[1]]
      first_part <- name_split[1]
      # cat("\n First part: ", first_part)
      
      if (first_part %in% c("peri", "loh")) {
        target_feat <- paste(name_split[1:2], collapse = "_")
      } else {
        target_feat <- first_part
      }
      cat("\n Target_feat: ", target_feat)
        
      # Read the CSV file
      feature_df <- read.csv(feature_file, stringsAsFactors = FALSE, row.names = NULL) %>% 
        select(-X)
      
      # Join the dfs
      feat_joind_df <- feature_df %>%
        left_join(
          gene_annotations %>% 
            select(c("gene_name", "seqnames", "arm")), 
          by = c("Feature" = "gene_name")
          ) %>%
        rename(
          "Chr" = "seqnames",
          "Arm" = "arm"
        ) %>% 
        drop_na(Chr) %>%
        mutate(
          chrm_arm = paste0(Chr, Arm),
          Target = target_feat
        ) %>% 
        select(-c("Chr", "Arm")) %>% 
        arrange(desc(Gain))
        
      # Save to the complete folder
      complete_df_name <- paste0(complete_imp_folder, "/complete_", file_name)
      # write.csv(feat_joind_df, complete_df_name, row.names = FALSE, )
      
      # Append to the fully complete df
      complete_cancer_type_imp_df <- rbind(complete_cancer_type_imp_df, feat_joind_df)
        
        # Check if the feature is an aneuploidy (ends with q or p)
      if (substr(target_feat, nchar(target_feat), nchar(target_feat)) %in% c("q", "p")) {
        # cat("\n Target_feat is an aneuploidy: ", target_feat)

        # Exclude the target feature from the dataframe
        filt_feat_joind_df <- feat_joind_df %>% 
          filter(
            chrm_arm != target_feat
          ) 
        
        # Save the modified dataframe
        filtered_df_name <- paste0(filt_imp_folder, "/filt_", file_name)
        # write.csv(filt_feat_joind_df, filtered_df_name, row.names = FALSE)
        
        # Append the fully filtered df
        filtered_cancer_type_imp_df <- rbind(filtered_cancer_type_imp_df, filt_feat_joind_df)
        
      }
      else {
        # Append the fully filtered df with the complete df
        filtered_cancer_type_imp_df <- rbind(filtered_cancer_type_imp_df, feat_joind_df)
        
        # save the file to the filtered folder
        filtered_df_name <- paste0(filt_imp_folder, "/filt_", file_name)
        # write.csv(feat_joind_df, filtered_df_name, row.names = FALSE)
      }
  }
  
  # Save the full complete cancer type feature importance df
  full_complete_cancer_feat_imp_name <- paste0(feat_imp_folder, "/full_complete_", cancer, "_feat_imp.csv")
  # write.csv(complete_cancer_type_imp_df, full_complete_cancer_feat_imp_name, row.names = FALSE)
  
  # Save the full filtered cancer type feature importance df
  full_filtered_cancer_feat_imp_name <- paste0(feat_imp_folder, "/full_filtered_", cancer, "_feat_imp.csv")
  # write.csv(filtered_cancer_type_imp_df, full_filtered_cancer_feat_imp_name, row.names = FALSE)
  
  # Filter the cancer type feat imp df to the top genes only
  top_complete_feat_imp_df <- complete_cancer_type_imp_df %>%
    group_by(Target) %>%
    slice_max(Gain, n = 1) %>%
    ungroup()
  
  top_filtered_feat_imp_df <- filtered_cancer_type_imp_df %>%
    group_by(Feature) %>%
    slice_max(Target, n = 1) %>%
    ungroup()
}
```




